apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: <name>
  namespace: <namespace>
spec:
    scaleTargetRef:
      name: <target_reference>
    triggers:
    - type: <even source type>
      metadata:
        <event source metadata>